INSERT INTO Car(ID, MODEL, CARYEAR, CARTYPE, PASSENGERCOUNT, CARRYINGCAPACITY) VALUES (1, 'Audi A5', 2010, 'PASSCAR', 4, 0.0)
INSERT INTO Car(ID, MODEL, CARYEAR, CARTYPE, PASSENGERCOUNT, CARRYINGCAPACITY) VALUES (2, 'BMW M5', 2010, 'PASSCAR', 4, 0.0)
INSERT INTO Car(ID, MODEL, CARYEAR, CARTYPE, PASSENGERCOUNT, CARRYINGCAPACITY) VALUES (3, 'Volvo', 2007, 'TRUCK', 0, 150.20)